<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OpenVSA.TestHarness.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenVSA.TestHarness\OpenVSA.TestHarness.csproj" />
    <ProjectReference Include="..\..\src\OpenVSA.Hal.Sim\OpenVSA.Hal.Sim.csproj" />
  </ItemGroup>

</Project>
